// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package model

import (
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type favorite_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var FavoriteBinding = favorite_EntityInfo{
	Entity: objectbox.Entity{
		Id: 2,
	},
	Uid: 3219607399202547460,
}

// Favorite_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Favorite_ = struct {
	Id          *objectbox.PropertyUint64
	Name        *objectbox.PropertyString
	Description *objectbox.PropertyString
	CreatedAt   *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &FavoriteBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &FavoriteBinding.Entity,
		},
	},
	Description: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &FavoriteBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &FavoriteBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (favorite_EntityInfo) GeneratorVersion() int {
	return 3
}

// AddToModel is called by ObjectBox during model build
func (favorite_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Favorite", 2, 3219607399202547460)
	model.Property("Id", 6, 1, 5136897829056098986)
	model.PropertyFlags(8193)
	model.Property("Name", 9, 2, 4042078010283640065)
	model.Property("Description", 9, 3, 7562740079138254850)
	model.Property("CreatedAt", 9, 4, 7319088374736491896)
	model.EntityLastPropertyId(4, 7319088374736491896)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (favorite_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Favorite).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (favorite_EntityInfo) SetId(object interface{}, id uint64) {
	object.(*Favorite).Id = id
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (favorite_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (favorite_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Favorite)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetDescription = fbutils.CreateStringOffset(fbb, obj.Description)
	var offsetCreatedAt = fbutils.CreateStringOffset(fbb, obj.CreatedAt)

	// build the FlatBuffers object
	fbb.StartObject(4)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetDescription)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetCreatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (favorite_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}
	var id = table.GetUint64Slot(4, 0)

	return &Favorite{
		Id:          id,
		Name:        fbutils.GetStringSlot(table, 6),
		Description: fbutils.GetStringSlot(table, 8),
		CreatedAt:   fbutils.GetStringSlot(table, 10),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (favorite_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Favorite, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (favorite_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	return append(slice.([]*Favorite), object.(*Favorite))
}

// Box provides CRUD access to Favorite objects
type FavoriteBox struct {
	*objectbox.Box
}

// BoxForFavorite opens a box of Favorite objects
func BoxForFavorite(ob *objectbox.ObjectBox) *FavoriteBox {
	return &FavoriteBox{
		Box: ob.InternalBox(2),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Favorite.Id property on the passed object will be assigned the new ID as well.
func (box *FavoriteBox) Put(object *Favorite) (uint64, error) {
	return box.Box.Put(object)
}

// PutAsync asynchronously inserts/updates a single object.
// When inserting, the Favorite.Id property on the passed object will be assigned the new ID as well.
//
// It's executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "Put & Forget:" you gain faster puts as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
//
// In situations with (extremely) high async load, this method may be throttled (~1ms) or delayed (<1s).
// In the unlikely event that the object could not be enqueued after delaying, an error will be returned.
//
// Note that this method does not give you hard durability guarantees like the synchronous Put provides.
// There is a small time window (typically 3 ms) in which the data may not have been committed durably yet.
func (box *FavoriteBox) PutAsync(object *Favorite) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Favorite.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Favorite.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *FavoriteBox) PutMany(objects []*Favorite) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *FavoriteBox) Get(id uint64) (*Favorite, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Favorite), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *FavoriteBox) GetMany(ids ...uint64) ([]*Favorite, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Favorite), nil
}

// GetAll reads all stored objects
func (box *FavoriteBox) GetAll() ([]*Favorite, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Favorite), nil
}

// Remove deletes a single object
func (box *FavoriteBox) Remove(object *Favorite) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *FavoriteBox) RemoveMany(objects ...*Favorite) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Favorite_ struct to create conditions.
// Keep the *FavoriteQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *FavoriteBox) Query(conditions ...objectbox.Condition) *FavoriteQuery {
	return &FavoriteQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Favorite_ struct to create conditions.
// Keep the *FavoriteQuery if you intend to execute the query multiple times.
func (box *FavoriteBox) QueryOrError(conditions ...objectbox.Condition) (*FavoriteQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &FavoriteQuery{query}, nil
	}
}

// Query provides a way to search stored objects
//
// For example, you can find all Favorite which Id is either 42 or 47:
// 		box.Query(Favorite_.Id.In(42, 47)).Find()
type FavoriteQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *FavoriteQuery) Find() ([]*Favorite, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Favorite), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *FavoriteQuery) Offset(offset uint64) *FavoriteQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *FavoriteQuery) Limit(limit uint64) *FavoriteQuery {
	query.Query.Limit(limit)
	return query
}
