// Code generated by ObjectBox; DO NOT EDIT.

package model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(3)

	model.RegisterBinding(TaskBinding)
	model.RegisterBinding(FavoriteBinding)
	model.LastEntityId(2, 3219607399202547460)

	return model
}
